#!/usr/bin/env python
#
# This node takes a ground truth pose publishing system and converts it to the
# noisy "odom -> base_link" + "map -> odom" corrections when localisation
# approach typical in robotics.
#
# "map -> odom" will be the start pose if 'ground_truth' is False, otherwise it
# will be the delta between our generated noisy "odom -> base_link" link and
# the true pose.
#
# Noise model is basic zero-mean Gaussian noise on velocity, but scaled by the
# velocity.  This leads to desirable results like 0 velocity having no noise /
# drift, and is tolerable within our velocity limits. May look at this making
# something more mature in the future. Current:
#       Linear vel noise = N(0, linear_vel * noise_linear)
#       Angular vel noise = N(0, angular_vel * noise_angular)

import benchbot_spatial as sp
import numpy as np
import rospy
from nav_msgs.msg import Odometry


class PoseNoisifier(object):

    def __init__(self):
        self.in_topic_odom = rospy.get_param("in_topic_odom", "/odom_raw")
        self.in_frame_odom = rospy.get_param("in_frame_odom", "odom_raw")
        self.in_frame_robot = rospy.get_param("in_frame_robot",
                                              "base_link_raw")

        self.out_topic_odom = rospy.get_param("out_topic_odom", "/odom_raw")
        self.out_frame_map = rospy.get_param("out_frame_map", "map")
        self.out_frame_odom = rospy.get_param("out_frame_odom", "odom")
        self.out_frame_robot = rospy.get_param("out_frame_robot", "base_link")

        self.ground_truth = rospy.get_param("ground_truth", False)

        self.noise_angular = rospy.get_param("noise_angular", 0.1)
        self.noise_linear = rospy.get_param("noise_linear", 0.1)

        self.start_pose = rospy.get_param("start_pose",
                                          "1,0,0,0,0,0,0")  # w,x,y,z,X,Y,Z
        self._start_pose_SE3 = sp.wxyzXYZ_to_SE3(
            *np.array([float(x.strip()) for x in self.start_pose.split(',')]))

        self._pub_odom = rospy.Publisher(self.out_topic_odom,
                                         Odometry,
                                         queue_size=1)
        self._sub_odom = rospy.Subscriber(self.in_topic_odom, Odometry,
                                          self.pub)

        self._accumulated_noise = np.eye(4)

    def pub(self, odom_msg):
        # Translate our clean odom into a noisy odom
        noisy_odom = np.matmul(sp.pose_msg_to_SE3(odom_msg.pose),
                               self._accumulated_noise)

        # Define "localisation" transform from map frame to odom based on our
        # mode
        localisation = (np.matmul(np.linalg.inv(self._accumulated_noise),
                                  self._start_pose_SE3)
                        if self.ground_truth else self._start_pose_SE3)

        # Publish our messages
        # TODO

        # Update accumulated noise
        # TODO


if __name__ == '__main__':
    rospy.init_node("noisify_pose")

    pn = PoseNoisifier()

    rospy.spin()
