#!/usr/bin/env python

from __future__ import print_function

from colorama import init, Fore
import rospy
import tf2_ros
import sys

STRING_WELCOME = """
Welcome to the BenchBot Real World Environment Builder. This script will help
you create an environment definition file in the format BenchBot requires, for
your own real robot platform & environment.

Please ensure you have the following before creating an environment file:
    - A space where you intend to run repeatable experiments
    - A real robot platform capable of running ROS
    - A ground truth system that publishes the 'map' to 'odom' transform in ROS
"""

if __name__ == "__main__":
    # Handle arguments

    # Print information string
    init(autoreset=True)
    print(STRING_WELCOME)

    # Ensure everything we require is running / setup
    print("Creating a ROS node ... ")
    rospy.init_node('benchbot_environment_creator')
    print("\t%sDone.\n" % Fore.GREEN)
    print("Checking 'map' to 'odom' transform is being published ... ")
    try:
        tf_buff = tf2_ros.Buffer()
        tf_list = tf2_ros.TransformListener(tf_buff)
        tf_buff.lookup_transform('odom', 'map', 0, rospy.Duration(3))
    except Exception as e:
        print("\t%sERROR: failed to find a current transform from "
              "'map' to 'odom'. Exception:\n\t%s'" % (Fore.RED, e))
        sys.exit(1)
    print("\t%sDone.\n" % Fore.GREEN)

    # Hand off to the main environment building process

    # Dump environment data to file
